### ISSUE TITLE
Syncing tabs between pages

### ISSUE THREAD

**Issue by Elpunical** [jhildenbiddle/docsify-tabs#17]
Hi, do you know if there's a way to sync tabs between multiple pages instead of just one page?

**Comment by jhildenbiddle** [comment]
Hey @Elpunical,

Currently this isn't possible, but it could be added easily enough.

My first inclination is to simply make this the new default behavior when `sync` is `true`. This could present an issue for sites that require the current behavior of only syncing tab selection on the current page, but the likelihood of that seems low. If/when this happens, I can always update the `sync` option to accept a string value like `page` instead of `true/false`.

Adding this to the backlog.

**Comment by jhildenbiddle** [comment]
@Elpunical --

This functionality has been added in the latest release. It is the new default behavior when `sync` is set to `true`.
