### ISSUE TITLE
Reopen #18

### ISSUE THREAD

**Issue by phuongbag** [jhildenbiddle/docsify-tabs#19]
You can try this code: https://hastebin.com/dewobogepe.md
and this is image https://imgur.com/a/GRTbqkH - sorry for late respone and the other website is down because i upload it to main domain and removed the plugin. (Still need to use)

**Comment by phuongbag** [comment]
Sorry for lack of info - here is a quick update:
Using latest docsify and these plugin



<script src="//unpkg.com/docsify@4.9.4/lib/docsify.min.js"></script>
--
  | <script src="//unpkg.com/docsify@4.9.4/lib/plugins/search.min.js"></script>
  | <script src="//unpkg.com/docsify@4.9.4/lib/plugins/external-script.min.js"></script>
  | <script src="//unpkg.com/docsify-pagination@2.4.0/dist/docsify-pagination.min.js"></script>

**Comment by jhildenbiddle** [comment]
@phuongbag --

I have tested the linked markdown file with the specified plugins on Edge 18 (EdgeHTML/Chakra engines) and Edge 80 (Chromium engine). I am not able to reproduce the behavior shown in the screenshots.

To try and isolate the issue, load *only* the latest versions of docsify and docsify-tabs (JS) as well as your theme (CSS). Disable all other plugins CSS applied via `<link>` and `<style>` tags. If the issue does not appear, then you the scrollbars behavior you're seeing is caused by some other plugin and/or stylesheet.

Also, please don't create new issues as a means of re-opening issues. Instead, just add your comment(s) to the closed issue and, if warranted, the repo owner(s) can reopen the issue.

**Comment by phuongbag** [comment]
found the problem - I followed the installation of your and add 2 type of docsify js

im using this <script src="//unpkg.com/docsify@4.9.4/lib/docsify.min.js"></script>
and add your scrip too so it bugging between those.
