### ISSUE TITLE
Hyperlink to tab

### ISSUE THREAD

**Issue by markbattistella** [jhildenbiddle/docsify-tabs#34]
Maybe I've missed it somewhere, but it would be cool to be able to link to a tab section and to an active tab.

Having a link to http://localhost:3000/#/newPage?id=windows

And it jumping to the `newPage` document, and activating the `windows` tab

**Comment by jhildenbiddle** [comment]
HI @markbattistella.

Should be easy enough to add, but I have some concerns about treating tabs as anchor links. Auto-scrolling a tab set to the top of the viewport means site visitors will arrive on a page without context for the tab content they are viewing.

Is the goal to allow navigating to tab sets from other sites or to jump directly to tab sets from links in your own site docs?

**Comment by markbattistella** [comment]
I think it may have been a bug when I was doing it locally but on the live environment it works.

But the intention was that you would have the user be pointed into the tab, and then the heading without having to click in

**Comment by jhildenbiddle** [comment]
@markbattistella Well, glad it's fixed! :)

Thanks for taking the time to file the PR. Much appreciated.

**Comment by A-Circle-Zhang** [comment]
Hi @jhildenbiddle , thank you for developing and maintaining `docsify-tabs`.

`setActiveTabFromAnchor` is not working with routerMode: 'history', which use url query to mark an anchor instead of url hash.
so I just replace `window.location.hash` with `window.location.search` for my project.

I think there should be a conditional statement of routerMode in `setActiveTabFromAnchor` function in `index.js`.

**Comment by jhildenbiddle** [comment]
Hi @A-Circle-Zhang --

I've made the necessary change on the [dev](https://github.com/jhildenbiddle/docsify-tabs/tree/dev) branch. Everything seems to work on my end with `routeMode: "history"`. If you can confirm on your end, I will publish a point release ASAP.

Thanks!
