### ISSUE TITLE
Doesn't work on pages linked via `alias`

### ISSUE THREAD

**Issue by oeway** [jhildenbiddle/docsify-tabs#37]
Hi, I found that the tabs won't show on pages set via the [alias](https://docsify.js.org/#/configuration?id=alias).

For example, if I have some tabs in an markdown from an external github repo, and I used the markups for tab, it doesn't work:
```js
window.$docsify = {
  alias: {
    '/changelog':
      'https://raw.githubusercontent.com/docsifyjs/docsify/master/CHANGELOG',
  },
};

```

If I copy and paste the same content to a relative file path under the current folder, then it works.

[Here](https://deploy-preview-400--imjoy.netlify.app/docs/#/api?id=apiexport) is a real example using alias and the tabs failed to render, and this is a [working example](https://deploy-preview-200--imjoy.netlify.app/docs/#/api?id=apiexport).

**Comment by jhildenbiddle** [comment]
Hi @oeway --

Happy to help, but I don't see a changelog link on either the real or working example you provided above.

It's worth mentioning that the URL you're using for the changelog is incorrect (it return a 404 error). The correct URLs includes the extension:

```js
window.$docsify = {
  alias: {
    '/changelog':
      'https://raw.githubusercontent.com/docsifyjs/docsify/master/CHANGELOG.md',
  },
};
```

**Comment by oeway** [comment]
Hi @jhildenbiddle Thank you!
Sorry for the confusion, it was just for illustration. For the real example,  see [here](https://github.com/imjoy-team/ImJoy/blob/c4daff2d65e7ac881e3e6db44e05789094412854/docs/index.html#L64) for the configuration, and [here](https://deploy-preview-400--imjoy.netlify.app/docs/#/api?id=apiexport) is the rendered version which isn't working. I have a working version [here](https://deploy-preview-200--imjoy.netlify.app/docs/#/api?id=apiexport) which loads the markdown from a relative path.

**Comment by jhildenbiddle** [comment]
@oeway --

One thing I noticed is that raw.githubusercontent.com sets `Content-Type` to `text/plain; charset=utf-8` in the response for markdown files while other hosts (like imjoy.io) set that value to `text/markdown`. I'm not sure if this is the issue, but testing is easy enough by using a host the sets the `Content-Type` header appropriately for your `alias`. Fortunately, jsDelivr already hosts your repo's content (since it hosts all GitHub content) and sets `Content-Type` to `text/markdown; charset=utf-8`.

```
https://cdn.jsdelivr.net/gh/imjoy-team/ImJoy/docs/api.md
```

Let me know if that solves the issue. If not, then we'll determine nexts steps.

**Comment by oeway** [comment]
Hi @jhildenbiddle Thanks a lot for figuring out the difference, I just tested by using the jsdelivr url (great tip! BTW), and it doesn't seem to work, I still go the same result

**Comment by jhildenbiddle** [comment]
Hi @oeway --

Been a while, but I'm (finally) getting around to unresolved GitHub issues. Apologies for the delay.

The issue appears to be related to loading content from another domain and not specifically with the use of an alias. To verify, try creating an alias to a markdown file that contains a tab set on the same domain as your `index.html`. You will see that tabs are rendered as expected.

This is a docsify-related issue that cannot be resolved by docsify-tabs (or any other plugin). My recommendation is to create an [issue in the docsify repo](https://github.com/docsifyjs/docsify/issues) so that it can be addressed properly. I am happy to continue the investigation there once the issue has been created.

Thanks!

**Comment by calumk** [comment]
> 

Opened an issue https://github.com/docsifyjs/docsify/issues/1711

**Comment by oeway** [comment]
@calumk Thanks!
