### ISSUE TITLE
Nested Tabs - almost works

### ISSUE THREAD

**Issue by gotjoshua** [jhildenbiddle/docsify-tabs#5]
In the process of setting up an alternative version of [markdown.md](https://github.com/jhildenbiddle/docsify-themeable/blob/master/docs/markdown.md)
visible here:
https://docs.1zm.in/#/markdown
[markdown.md code here](https://github.com/onezoomin/docsify-themeable/blob/master/docs/markdown.md)

i realized that the tabs don't quite look right if you nest them:
https://docs.1zm.in/#/nestedtabs

First Tab looks quite broken:
![firsttabverybroken](https://user-images.githubusercontent.com/8686454/51272254-8e66e000-19c1-11e9-8275-bef4b2ece32a.png)
The last tab almost looks ok:
![lasttabalmostok](https://user-images.githubusercontent.com/8686454/51272255-8e66e000-19c1-11e9-8009-90de5249a42c.png)

So it seems that it might only need small adjustments to work correctly.

**Comment by jhildenbiddle** [comment]
Hi @gotjoshua.

Per the [Features/Limitations](https://jhildenbiddle.github.io/docsify-tabs/#/?id=features) section of the docs:

> **Limitations**
> 
> * Nested tabsets (i.e. tabs within tabs) are not supported.

Nested tabsets are challenging as a result of how markdown needs to be parsed and HTML needs to be generated/inserted within the docsify plugin system. I'm sure it can be done, but after a few failed attempts I decided to move on assuming it wasn't a common use case for tabsets. If there is a strong need for nested tabsets, let me know and we can discuss further.

**Comment by gotjoshua** [comment]
Well, strong need would be a stretch...
Its a fringe case and if you consciously chose not to support it, i think
thats totally fine (sorry, i missed that in the docs).
It just seemed like it wasn't so far off, but I didn't dive deep enough
into the code to see how challenging it would be to implement.

Thanks for the great theme and plugin! Keep up the good work!
Cheers

>

**Comment by jhildenbiddle** [comment]
I appreciate you taking the time to file the issue. :smile:

I have updated the [Markdown section](https://jhildenbiddle.github.io/docsify-themeable/#/markdown) on the [docsify-themeable](https://jhildenbiddle.github.io/docsify-themeable/#/) website with the tabs per your suggestion. Great idea.

Thanks again, @gotjoshua.

**Comment by gotjoshua** [comment]
Great that you like the tabbed markdown cheatsheet!

A last thought about nested:

Could it work to add an identifier to the comment blocks for start and end?
Not required, but always checked for in case nested tabs are wished.
eg:
```html
<!-- tabs:start<<<OUTER -->
#### **outer tab containing nested tabs**
content above tabs
<!-- tabs:start<<<INNER -->
#### **inner tab contents**
<!-- tabs:end:INNER-->
#### **2nd outer tab without nested tabs**
content
<!-- tabs:end:OUTER -->
```
I guess I'm thinking like ["Heredoc" multiline string syntax](https://stackoverflow.com/a/36525712/2919380)

Could this strategy make parsing more possible?

(I looked at the index.js code, but I don't have time to offer a PR, sorry)

**Comment by jhildenbiddle** [comment]
Possibly, but that would add complexity for the end user which I would like to avoid if possible.

If nested tabs becomes an issue that needs to be solved, then I would most likely start with a library like [balanced-match](https://www.npmjs.com/package/balanced-match) to (hopefully) make parsing tabsets easier. I didn't do this initially because parsing is pretty easy when you aren't worried about nested tabs and I didn't want to add a dependency unnecessarily.

For now, I'll chalk this up as a +1 for nested tabs. The other issue that needs to be resolved is tab wrapping on small screens. I'd like to address both of these issues at some point in the future, but for now I'm focused on other projects. If/when nested tabsets becomes an issue for you, give me a shout and I'll see if I have the bandwidth to make the necessary updates.

**Comment by jhildenbiddle** [comment]
FYI, nested tabs are now supported as of v1.6.0.

**Comment by gotjoshua** [comment]
> nested tabs are now supported

👌👍🤩🙏
