### ISSUE TITLE
Search Functionality in Tabs Tables

### ISSUE THREAD

**Issue by virnahar** [jhildenbiddle/docsify-tabs#54]
Search plugin is not able to search in the tabs tables.

**Comment by jhildenbiddle** [comment]
I am unable to reproduce this error. 

Try loading your site in a private browsing window. This will force your search index data to be recreated when the site loads. If this is solves your problem, then the issue was a stale search data stored. You can manually delete this data by deleting the `docsify.search.*` items from your localStorage.
