### ISSUE TITLE
VuePress

### ISSUE THREAD

**Issue by timaschew** [jhildenbiddle/docsify-tabs#6]
I saw you offered to migrate your plugin to VuePress (https://github.com/vuejs/vuepress/issues/851)

Did you use VuePress for anything or what was your intention to do the port? 
What do you think about VuePress (now)?

**Comment by jhildenbiddle** [comment]
I haven't used it for a project, so can't really say one way or the other. 

At the time I offered to port docsify-tabs, VuePress was fairly new. Now it's been around for a while and has a substantial following. 

Here a few random thoughts:

* It's not as easy to setup as docsify, especially when you consider the scenario of a repo with an existing README that you just want to turn into a site quickly. This is the scenario where I think docsify really shines, albeit at the cost of SEO. For example, to use GitHub pages you simply create a `\docs` folder, add an `index.html` file to it, and specify the `README.me` URL as as the `window.$docsify.homepage` value. Done.

* It's not easy to change the default theme. In order to [customize the default theme](https://vuepress.vuejs.org/guide/custom-themes.html#customizing-the-default-theme), devs have the eject which is a lousy experience IMHO. 

  >  Note, however, once you eject, you are on your own and won't be receiving future updates or bug fixes to the default theme even if you upgrade VuePress.

   Something like docsify-themeable would be really helpful for people who want to customize the default theme without having to eject. Vue-themeable?

* VuePress 1.0 has been in alpha for over six months now. I haven't been following the project closely enough to know if this means progress is moving slowly or lots of progress is being made and that just takes time, but I'd want to understand this before investing in it.

**Comment by timaschew** [comment]
>At the time I offered to port docsify-tabs, VuePress was fairly new.

Okay, got it :)

> It's not as easy to setup as docsify, ...

While that's true, there are so many free services and tools which allows you to run some build scripts. Netlify for instance. But I understand even this can be an obstacle for some users.

> It's not easy to change the default theme

I agree. It would be awesome to have something like docsify-themeable for VuePress.

> VuePress 1.0 has been in alpha for over six months now

At the beginning I was a bit surprised as well. But they have [frequent releases](https://github.com/vuejs/vuepress/releases). I guess they just want to have a mature API before the release the beta or even the final one.

**Comment by jhildenbiddle** [comment]
I don't have a lot of free time to dedicate to new projects at the moment, but perhaps creating a project like docisfy-themeable for VuePress would be interesting at some point in the future.

In the meantime, I may consider VuePress for a near-term project in order to give it a test run. Curious to see how the 1.0 alphas are progressing.

**Comment by timaschew** [comment]
Actually did you see this: https://v1.vuepress.vuejs.org/theme/option-api.html#extend 

Also this is a good page to see their plan: https://github.com/vuejs/vuepress/projects/1
