### ISSUE TITLE
Doesn't seems to work inside _sidebar.md

### ISSUE THREAD

**Issue by trusktr** [jhildenbiddle/docsify-tabs#7]
I wanted to make my sidebar tabbed, but it appears to have no effect in there.

**Comment by jhildenbiddle** [comment]
@trusktr --

Correct. The plugin currently does not parse the sidebar content because docsify does not pass this content to any of the [plugin hooks](https://docsify.js.org/#/write-a-plugin). Long story short, it isn't possible unless some significant changes were made to docisfy's plugin system. Until then, if you want to render tabs within your sidebar you will need to use your own combination of HTML, CSS, and (potentially) JavaScript depending on what functionality you need.

Hope this helps.
